name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build_and_package:
    name: Build and Package
    needs: publish_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: macos
          - os: windows-latest
            target: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/ghc

      - name: Pack
        shell: bash
        run: curl -sSL https://raw.githubusercontent.com/nalchevanidze/hconf/main/scripts/pack.sh | sh -s .

      - name: Test Binary
        shell: bash
        run: curl -sSL https://raw.githubusercontent.com/nalchevanidze/hconf/main/scripts/test.sh | sh -s .

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish_release.outputs.upload_url }}
          asset_path: hconf.zip
          asset_name: hconf-${{ matrix.target }}.zip
          asset_content_type: application/zip
